### ISSUE TITLE
[3.2.3] Mechanisms for sharing medatata and other operations-oriented information are established between the federated EGA node and Central EGA - Level 3

### ISSUE THREAD

**Issue by lauportell** [inab/fega-mm#10]
Mallory: What is meant by "common data standards" here? Want to be clear that data (i.e. sensitive human data) is not exchanged between CEGA and FEGA nodes.

**Comment by scapella** [comment]
New wording: Communication interfaces are well defined. Information, operations-oriented & public metadata, e.g. study metadata, accessions, can be exchanged between the federated EGA node and Central EGA in a manual way.

**Comment by scapella** [comment]
IMPORTANT for future references: As FEGA grows, it will be necessary to have a standardized way to exchange such information.
