### ISSUE TITLE
[2.1.2] Risk and Vulnerability Analysis perfomed (Level 5)

### ISSUE THREAD

**Issue by lauportell** [inab/fega-mm#35]
Błażej:
Part of ISO 27001, ISO has higher demands than periodic review only. This and Previous fields should be fliped.

**Comment by lauportell** [comment]
Remove the HIPPA and ISO27001 certificate from level 4

**Comment by malloryfreeberg** [comment]
Suggested new indicators:

4. Approval of risk management plan obtained in accordance to the hosting institution of the Federated EGA node
5. Periodic review of the risk management plan and update of the Risk and Vulnerability Analysis, when required. Contribute towards the shared knowledge base of the Federated EGA ecosystem
