### ISSUE TITLE
[2.3.1] Data Processing Agreement (DPA) is available to users

### ISSUE THREAD

**Issue by lauportell** [inab/fega-mm#36]
Błażej:
Case when DPA is not needed?

**Comment by kjellp** [comment]
There may be several cases were a Submitter do not need a DPA with the FEGA node Service Provider origanisation, for instance they are both the same organisation. But a FEGA node still need to be able to have a DPA template available for any other Submitters that may likely desire to submit data to their node. It seems very unlikely according to GDPR that a FEGA node Service Provider organisation will have all DPA concerns sorted out in advance towards all possible submitters (other research and health institutions in the country and possibly internationally).

For FEGA Community nodes, with a more limited scope, the case may be more realistic that all submitters in scope will be from the SP's own organisation. Is the MM intended to cover the FEGA Community node scope as well?

**Comment by amycurwin** [comment]
@blazejmarciniak to add you to the conversation in case you want to add or comment

Responding to @kjellp I think the MM is not meant to cover Community nodes. That will be a different monster to tackle as the cases will vary greatly

**Comment by blazejmarciniak** [comment]
We are considering two approaches, the first is a regulation at the national level (parliamentary act) regulating the use of this kind of repository for data storage and sharing.
Plan B is: repository operates based on the terms of service, which define the rules for handling data and the obligations of the parties.
BTW. At the moment, we are considering storing and sharing scientific data from research projects not directly from hospitals.

**Comment by lauportell** [comment]
1.	None
2.	Initial template of the Data Processing Agreement (DPA) is drafted taking into account local regulations
3.	Data Processing Agreement template incorporates elements from the Federated EGA Ecosystem to ensure consistency
4.	Data Processing Agreement template is approved by the institution hosting the Federated EGA Node, and it can be distributed to submitters
5.	Periodically review use and update to reflect changes in the existing regulations and/or new working procedures in the Federated EGA Node

Mallory and Kjell will look at it to redefine the maturity levels.
This indicator will be important and not essential.

**Comment by kjellp** [comment]
Revised suggestion from me:

1. None
2. Initial template of a Data Processing Agreement (DPA) is drafted taking into account local regulations, intended for data submission cases that would require a DPA.
3. Data Processing Agreement template is approved by the institution hosting the Federated EGA Node, and it can be distributed to submitters
4. Data Processing Agreement template incorporates elements from the Federated EGA Ecosystem to ensure consistency
5. Periodically review use and update to reflect changes in the existing regulations and/or new working procedures in the Federated EGA Node

**Comment by lauportell** [comment]
@malloryfreeberg for some reason I can't assign you this issue, but hopefully you can see this comment.

**Comment by kjellp** [comment]
Looks good to me :)

**Comment by lauportell** [comment]
1. None
2. Initial Data Processing Agreement (DPA) template is drafted, taking into account local regulations, for data submission cases that require a DPA
3. Data Processing Agreement template incorporates elements from the Federated EGA Ecosystem to ensure consistency
4. Data Processing Agreement template is approved by the institution hosting the Federated EGA Node and can be distributed to submitters
5. Periodically review and update Data Processing Agreement template to reflect changes in existing regulations and/or new working procedures in the Federated EGA Node
