### ISSUE TITLE
[3.1.3] Risk register/assessment implemented

### ISSUE THREAD

**Issue by lauportell** [inab/fega-mm#6]
Melissa: Should this be moved to the organisational section? A risk register seems like more of an organisational concept than a directly technical one.

Giselle: Interesting point.From my perspective both the risk register and the security breach/incident response plan address technical risk/issues to an extent but as you say perhaps both of these are more suited to Domain 1.

Mallory: One argument to keep the risk register in this domain is that it can include very low-level technical risks. For example, how FEGA staff manage login/passwords to FEGA infrastructure. The RR can also (depending on what the node wants) include higher-level organisational risks, but these are often covered in the DPIA (2.1.1). I vote to keep the RR in domain 3.

Melissa: That's an interesting point.  I'm thinking less about what the risk register can contain and more about the role it plays in an organization.  So, while training may involve some technical training, it would be considered "organizational" because it is about planning and setting up how the group works.  Doesn't a risk register perform in that same domain?

**Comment by MKonopkoELIXIR** [comment]
Add that it is connected to 1.1.1
