### ISSUE TITLE
[5.1.1] Internal node operation SOPs defined and documentation available

### ISSUE THREAD

**Issue by lauportell** [inab/fega-mm#67]
Propose changes for level 3 and 4

**Comment by malloryfreeberg** [comment]
From feedback collected from Norway, Finland, Germany, Spain, Sweden, Central EGA, FOSP [here](https://docs.google.com/document/d/1iytHl5QL2wE4MOaTyc44lnjJ57VOKwArSn3KrHUBZ3s/edit), 5.1.1 Level 5 says "SOPs audited & reviewed annually." but audited by who? We agreed this meant auditing internally, so the text should be changed to reflect this.
