### ISSUE TITLE
[5.1] Clarify SOP acronym

### ISSUE THREAD

**Issue by malloryfreeberg** [inab/fega-mm#76]
Feedback from Cambridge FEGA-thon:
"[5.1] Standard Operating Procedures -> Explain this is an SOP. As in Indicators it only uses SOP"

I interpret this to be a request to clarify the SOP acronym in the subdomain title as only the acronym is used in the indicator and level texts.

**Comment by lauportell** [comment]
I changed the indicator and this should be done already. Can you check and review it?

**Comment by malloryfreeberg** [comment]
LGTM (Looks Good To Me)
